config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes
  resources :menus
  
  get 'menus/:id/add_dish', to: "menus#add", as: "add_dish"


  delete 'menus/:id/remove_dish/:dish_id', to: "menus#remove", as:"remove_dish"

  post 'menus/:id/post_add', to: "menus#post_add", as:"post_dish"
  root "menus#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
    validates :name, presence: true
    validates :price, numericality: { only_integer: true}
    has_and_belongs_to_many :menus
end

app/models/menu.rb
class Menu < ApplicationRecord
    validates :name, presence: true, uniqueness: true, length: {minimum: 4}
    has_and_belongs_to_many :dishes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery # Same as above
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy]
  before_action :is_admin?, only: [:edit, :update, :new, :create, :delete]
  layout :choose_layout
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
      @dish.visits ||= 0
      @dish.visits = @dish.visits + 1
      @count = @dish.visits
      @dish.save
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:name, :cateogry, :visits, :price)
    end

    def choose_layout
      if current_user && current_user.admin?
        "admin"
      elsif current_user
        "manager"
      else
        "application"
      end
    end

    def is_admin?
      redirect_to root_path unless current_user.admin?
    end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy, :remove, :add, :post_add]
  before_action :authenticate_user!, only: [:edit, :update, :new, :create, :destroy, :show, :add, :remove]
  before_action :is_admin?, only: [:edit, :update, :new, :create, :delete, :add, :remove]
  layout :choose_layout 

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @dishes = Dish.all
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  def add
    @dishes = Dish.all
  end

  def post_add
    @ndish = Dish.find_by(id: params[:dishes][:id])
    if @ndish
      @menu.dishes << @ndish
      @menu.save
      redirect_to @menu, notice: 'A New Dish added in menu'
    else
      redirect_to @menu, notice: "No dish added as dish #{params[:dishes][:name]} doesnt, exists"
    end

    
  end
 
  def remove
    dish_id = params[:dish_id]
    @dish_rem = Dish.find_by(id:dish_id)
    @menu.dishes.delete(@dish_rem)

    redirect_to @menu
  end 
 

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name)
    end

    def choose_layout
      if current_user && current_user.admin?
        "admin"
      elsif current_user
        "manager"
      else
        "application"
      end
    end

    def is_admin?
      redirect_to root_path unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/dishes/_form.html.erb
<%= form_with(model: dish, local: true) do |form| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :cateogry %>
    <%= form.text_field :cateogry %>
  </div>


  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cateogry</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.name %></td>
        <td><%= dish.cateogry %></td>
        <td><%= dish.price %></td>
        <% if current_user && current_user.admin%>
          <td><%= link_to 'Show', dish %></td>
          <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
          <td><%= link_to 'Destroy', dish_path(dish), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%elsif current_user%>
          <td><%= link_to 'Show', dish %> </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p style="color:gray;text-align:right;"> No of visits : <%= @count %> </p>

<p>
  <strong>Name:</strong>
  <%= @dish.name %>
</p>

<p>
  <strong>Cateogry:</strong>
  <%= @dish.cateogry %>
</p>

<p>
  <strong>Price:</strong>
  <%= @dish.price %>
</p>

<p>
  <strong> Menus: </strong>
  <%@dish.menus.each do |menu| %>
    <%=menu.name%> |
  <%end%>
</p>

<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">RAILS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Menus ", menus_path, :style=>'color:white'%> &nbsp &nbsp
      </li>
      <li class="nav-item">
            <%= link_to " Dishes ", dishes_path, :style=>'color:white'%> &nbsp &nbsp
      </li>
    
      <li class="nav-item">
        <% if current_user %>
          <%= link_to 'SIGN-OUT', destroy_user_session_path, :style=>'color:white', method: :delete %>
        <%else%>
          <%= link_to 'REGISTER USER', new_user_registration_path, :style=>'color:white' %> &nbsp &nbsp
          <%= link_to 'SIGN-IN', new_user_session_path, :style=>'color:white' %>
        <%end%>
      </li>

      <li class="nav-item" style="margin-left:500px;">
        <% if current_user && current_user.admin%>
          <p style="color:orange;text-align:right;"> ADMIN</p>
        <%elsif current_user%>
          <p style="color:orange;text-align:right;"> MANAGER </p>
        <%end%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment01</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield%>
  </body>
</html>

app/views/layouts/manager.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/add.html.erb
<h3> Listing all possible dishes in our record </h3>

<% @dishes.each do |dish|%>
  <%=dish.id %> | <%= dish.name%>
  <br/>
<%end%>

<%= form_with scope: :dishes, url:post_dish_path(@menu), local: true do |form| %>
<p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
</p>
<p>
    <%= form.select :id, @dishes.map { |d| [d.name,d.id]} %>
</p>
<p>
    <%= form.submit 'Add to Menu' %>
</p>

<%end%>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Menus</h1>


<table border="1" style="margin-left:15px;"> 
  <thead>
    <tr>
      <th>Menu ID </th>
      <th>Name</th>
      <th> Show</th>
      <th> EDIT</th>
      <th> Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.id %></td>
        <td><%= menu.name %></td>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Show', menu %></td>
          <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
          <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif current_user %>
          <td><%= link_to 'Show', menu %> </td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Menu', new_menu_path %>
<button type="button" class="btn btn-danger"> <%= link_to 'Dishes Page', dishes_path, :style=>'color:white'%>  </button>
 

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>
<h4> Dishes</h4>
<% @menu.dishes.each do |dish| %>
  <%= dish.name %>  | <%= dish.price %>  |  <%= dish.cateogry%>   <button> <%= link_to "Remove dish", remove_dish_url(dish_id: dish.id), method: :delete, data: {confirm: "are you sure to remove this dish?"}  %> </button>
<br/><br/>

<%end%>
<br>

<% if current_user && current_user.admin %>
  
  <%= form_with scope: :dishes, url:post_dish_path(@menu), local: true do |form| %>
  <p>
    <%= form.select :id, @dishes.map { |d| [d.name,d.id]} %> &nbsp &nbsp
    <%= form.submit 'Add to Menu' %>

  </p>
  
  <%end%>  
<%end%>

<br/> <br/>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %> | 